title: Jeff Oliver
# logo:
# description: text below image
show_downloads: true
# find some theme information here: https://pages.github.com/themes/
# https://pages-themes.github.io/minimal/
# https://pages-themes.github.io/cayman/
theme: jekyll-theme-minimal

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-content-to-your-github-pages-site-using-jekyll
